// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Node struct {
	ID        uuid.UUID
	Type      sql.NullInt32
	CreatedAt time.Time
}

type NodeAlias struct {
	ID     int32
	NodeID uuid.NullUUID
	Alias  sql.NullString
}

type NodeDraft struct {
	ID        uuid.UUID
	Type      sql.NullInt32
	CreatedAt time.Time
}

type NodeHistory struct {
	ID        int32
	NodeID    uuid.NullUUID
	UpdatedAt time.Time
	Version   sql.NullInt32
	Body      pqtype.NullRawMessage
}

type Pipeline struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

type PipelineDraft struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

type PipelineHistory struct {
	ID            int32
	PipelineID    uuid.UUID
	NodesPerStage []int32
	UpdatedAt     time.Time
	Nodes         []uuid.UUID
	NodeVersions  []int32
	Version       sql.NullInt32
}
