// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getLatestNode = `-- name: GetLatestNode :one
SELECT n.id, n.type, n.created_at FROM node n
JOIN LATERAL (
  SELECT updated_at, version, body FROM node_history nh
  WHERE nh.node_id = n.id
  ORDER BY nh.version DESC LIMIT 1
) on TRUE
WHERE n.id = $1
`

func (q *Queries) GetLatestNode(ctx context.Context, id uuid.UUID) (Node, error) {
	row := q.db.QueryRowContext(ctx, getLatestNode, id)
	var i Node
	err := row.Scan(&i.ID, &i.Type, &i.CreatedAt)
	return i, err
}

const getLatestNodes = `-- name: GetLatestNodes :many
SELECT n.id, n.type, n.created_at FROM node n
JOIN LATERAL (
  SELECT updated_at, version, body FROM node_history nh
  WHERE nh.node_id = n.id
  ORDER BY nh.version DESC LIMIT 1
) on TRUE
WHERE n.id = ANY($1::uuid[])
`

func (q *Queries) GetLatestNodes(ctx context.Context, ids []uuid.UUID) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, getLatestNodes, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(&i.ID, &i.Type, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestPipeline = `-- name: GetLatestPipeline :one
SELECT id, pipeline_id, nodes_per_stage, updated_at, nodes, node_versions, version FROM pipeline_history
WHERE pipeline_id = $1
ORDER BY VERSION DESC
LIMIT 1
`

func (q *Queries) GetLatestPipeline(ctx context.Context, pipelineID uuid.UUID) (PipelineHistory, error) {
	row := q.db.QueryRowContext(ctx, getLatestPipeline, pipelineID)
	var i PipelineHistory
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		pq.Array(&i.NodesPerStage),
		&i.UpdatedAt,
		pq.Array(&i.Nodes),
		pq.Array(&i.NodeVersions),
		&i.Version,
	)
	return i, err
}

const getNodeHistory = `-- name: GetNodeHistory :one
SELECT id, node_id, updated_at, version, body FROM node_history
WHERE node_id = $1
ORDER BY version DESC
`

func (q *Queries) GetNodeHistory(ctx context.Context, nodeID uuid.NullUUID) (NodeHistory, error) {
	row := q.db.QueryRowContext(ctx, getNodeHistory, nodeID)
	var i NodeHistory
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.UpdatedAt,
		&i.Version,
		&i.Body,
	)
	return i, err
}

const getNodesHistory = `-- name: GetNodesHistory :many
SELECT id, node_id, updated_at, version, body FROM node_history
WHERE node_id = ANY($1::uuid[])
ORDER BY version DESC
`

func (q *Queries) GetNodesHistory(ctx context.Context, ids []uuid.UUID) ([]NodeHistory, error) {
	rows, err := q.db.QueryContext(ctx, getNodesHistory, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeHistory
	for rows.Next() {
		var i NodeHistory
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.UpdatedAt,
			&i.Version,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPipelineHistory = `-- name: GetPipelineHistory :many
SELECT id, pipeline_id, nodes_per_stage, updated_at, nodes, node_versions, version FROM pipeline_history
WHERE pipeline_id = $1
ORDER BY version DESC
`

func (q *Queries) GetPipelineHistory(ctx context.Context, pipelineID uuid.UUID) ([]PipelineHistory, error) {
	rows, err := q.db.QueryContext(ctx, getPipelineHistory, pipelineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PipelineHistory
	for rows.Next() {
		var i PipelineHistory
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			pq.Array(&i.NodesPerStage),
			&i.UpdatedAt,
			pq.Array(&i.Nodes),
			pq.Array(&i.NodeVersions),
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const addPipeline = `-- name: addPipeline :exec
WITH ins AS (
  INSERT INTO pipeline (id, created_at) 
  VALUES ($1, $2)
  RETURNING id
) INSERT INTO pipeline_history (
  pipeline_id, updated_at, nodes_per_stage, nodes, version
) SELECT $1, $2, $3, $4, 1 FROM ins
`

type addPipelineParams struct {
	PipelineID    uuid.UUID
	UpdatedAt     time.Time
	NodesPerStage []int32
	Nodes         []uuid.UUID
}

func (q *Queries) addPipeline(ctx context.Context, arg addPipelineParams) error {
	_, err := q.db.ExecContext(ctx, addPipeline,
		arg.PipelineID,
		arg.UpdatedAt,
		pq.Array(arg.NodesPerStage),
		pq.Array(arg.Nodes),
	)
	return err
}
